version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
  redis:
    image: redis
    restart: always
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"